[package]
name = "fzgrep"
version = "1.0.0"
authors = ["Andrii Semkiv <semkiv@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = "4.5.4"
env_logger = "0.11.3"
log = "0.4.21"
vscode-fuzzy-score-rs = { git = "https://github.com/semkiv/vs-code-fuzzy-score-rs.git", tag = "v0.2.6" }
walkdir = "2.5.0"
yansi = "1.0.1"

[dev-dependencies]
tempfile = "3.10.1"
