[package]
name = "fzgrep"
version = "0.1.0"
authors = ["Andrii Semkiv <semkiv@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
colored = "2.0.4"
env_logger = "0.10.0"
log = "0.4.20"
vscode-fuzzy-score-rs = { git = "https://github.com/semkiv/vs-code-fuzzy-score-rs.git", tag = "v0.2.2" }
