[package]
name = "fzgrep"
version = "1.1.1"
authors = ["Andrii Semkiv <semkiv@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.32"
env_logger = "0.11.7"
glob = "0.3.2"
log = "0.4.21"
vscode-fuzzy-score-rs = { git = "https://github.com/semkiv/vs-code-fuzzy-score-rs.git", tag = "v0.2.8" }
walkdir = "2.5.0"
yansi = "1.0.1"

[dev-dependencies]
tempfile = "3.19.1"
